In [1]:
import numpy as np

test = np.random.randint(0,10, (3,2,4)) # three layers of 2x4 matrices
print(test)

[[[8 3 1 0]
  [3 9 1 7]]

 [[0 0 8 4]
  [1 7 5 2]]

 [[1 5 7 7]
  [9 8 6 8]]]


In [2]:
test.transpose(0,2,1)

array([[[8, 3],
        [3, 9],
        [1, 1],
        [0, 7]],

       [[0, 1],
        [0, 7],
        [8, 5],
        [4, 2]],

       [[1, 9],
        [5, 8],
        [7, 6],
        [7, 8]]])

In [3]:
np.divide([0,0,0], [1,1,0])

C:\Users\jason\AppData\Local\Temp/ipykernel_16336/1998601296.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide([0,0,0], [1,1,0])


array([ 0.,  0., nan])

In [8]:
a = np.array([0,1,0])
b = np.array([1,1,0])
d = np.nan_to_num(a/b)
print(d)

[0. 1. 0.]


C:\Users\jason\AppData\Local\Temp/ipykernel_16336/534693295.py:3: RuntimeWarning: invalid value encountered in true_divide
  d = np.nan_to_num(a/b)
