In [10]:
import numpy as np

test = np.random.randint(0,10, (3,2,4)) # three layers of 2x4 matrices
print(test)

[[[3 7 0 1]
  [2 6 1 5]]

 [[0 9 2 9]
  [1 4 2 9]]

 [[3 2 3 1]
  [0 9 5 7]]]


In [13]:
b = [0.5, 0.5, 0.5, 0.5]  # 1x4
print(test @ b) # three layers of 2x4 @ 4x1 = three layers of 2,1 matrices
print((test@b).shape)

print(np.einsum('ijk,jk',test ,b))

[[ 5.5  7. ]
 [10.   8. ]
 [ 4.5 10.5]]
(3, 2)


ValueError: einstein sum subscripts string contains too many subscripts for operand 1